kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker/compose:1.28.0
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker-compose build
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
