version: "3.8"
services:
  website:
    build: .
    ports:
      - "8081:8080"
    environment:
      - "DEV=true"
      - "RUST_BACKTRACE=1"
    volumes:
      - .:/website
      - type: bind
        source: ./.cargo/
        target: /root/.cargo/
    restart: unless-stopped