version: "3.8"
services:
  website:
    build: .
    ports:
      - "8081:9090"
    environment:
      - "DEV=true"
      - "RUST_BACKTRACE=full"
    volumes:
      - .:/website
      # - type: bind
      #   source: ./.cargo/
      #   target: /root/.cargo/
    restart: unless-stopped
