version: "3.8"
services:
  website:
    image: alanp:latest
    build: .
    ports:
      - "8081:9090"
    environment:
      - "PATH_ROOT=/website"
    # volumes:
    #   - .:/website
      # - type: bind
      #   source: ./.cargo/
      #   target: /root/.cargo/
    restart: unless-stopped
